openapi: 3.0.0
info:
  title: Hobby shop
  description: Hobby shop
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /inventory:
    get:
      description: Gets the inventory items
      tags:
        - Inventory
      parameters:
        - in: query
          name: name
          description: Name of the inventory item
          schema:
            type: string
          required: true
      responses:
        200:
          description: List of inventory data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/InventoryGetOk'
        400:
          $ref: '#/components/responses/InvalidRequest'
        422:
          $ref: '#/components/responses/ValidationResponse'
    post:
      description: Adds an item in the inventory
      tags:
        - Inventory
      requestBody:
        description: Inventory data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryPostRequest'
      responses:
        201:
          description: Record ID of the created inventory item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryPostCreated'
        400:
          $ref: '#/components/responses/InvalidRequest'
        422:
          $ref: '#/components/responses/ValidationResponse'
  /inventory/{id}:
    get:
      description: Gets the inventory item with the specified ID
      tags:
        - Inventory
      parameters:
        - in: path
          name: id
          description: ID of the inventory item
          schema:
            type: string
          required: true
      responses:
        200:
          description: Inventory data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryGetOk'
        400:
          $ref: '#/components/responses/InvalidRequest'
        422:
          $ref: '#/components/responses/ValidationResponse'
    put:
      description: Update an inventory item
      tags:
        - Inventory
      parameters:
        - in: path
          name: id
          description: ID of the inventory item
          schema:
            type: string
          required: true
      requestBody:
        description: Inventory data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryPostRequest'
      responses:
        204:
          description: Update succeeded
        400:
          $ref: '#/components/responses/InvalidRequest'
        422:
          $ref: '#/components/responses/ValidationResponse'
components:
  responses:
    InvalidRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    ValidationResponse:
      description: Validation response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
  schemas:
    ErrorMessage:
      type: object
      properties:
        message:
          type: string
    InventoryGetOk:
      type: object
      properties:
        id:
          type: string
        short_name:
          type: string
        full_name:
          type: string
        status:
          type: string
          enum:
            - In stock
            - Unavailable
            - Discontinued
        stock:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    InventoryPostRequest:
      type: object
      properties:
        short_name:
          type: string
        full_name:
          type: string
        status:
          type: string
          enum:
            - In stock
            - Unavailable
            - Discontinued
        stock:
          type: integer
      required:
        - short_name
        - full_name
        - status
    InventoryPostCreated:
      type: object
      properties:
        id:
          type: string